import {PlayIcon} from '@sanity/icons/Play'
import {defineField, defineType} from 'sanity'

export const aboutPage = defineType({
  name: 'aboutPage',
  title: 'About page',
  type: 'document',
  icon: PlayIcon,
  groups: [
    {name: 'opening', title: 'Opening', default: true},
    {name: 'story', title: 'Story text'},
    {name: 'accessible', title: 'Accessible version'},
    {name: 'closing', title: 'Closing action'},
    {name: 'seo', title: 'Search & sharing'},
  ],
  fields: [
    defineField({
      name: 'openingLabel',
      title: 'Opening label',
      type: 'string',
      group: 'opening',
      initialValue: 'Lorem ipsum dolor',
      validation: (Rule) => Rule.required().max(60),
    }),
    defineField({
      name: 'openingHeadline',
      title: 'Opening headline',
      type: 'string',
      group: 'opening',
      initialValue: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      validation: (Rule) => Rule.required().max(120),
    }),
    defineField({
      name: 'openingNote',
      title: 'Opening note',
      type: 'string',
      group: 'opening',
      initialValue: 'Consectetur adipiscing',
      validation: (Rule) => Rule.required().max(60),
    }),
    defineField({
      name: 'windingHeadline',
      title: 'Winding headline',
      type: 'string',
      group: 'story',
      initialValue: 'Consectetur adipiscing elit.',
      validation: (Rule) => Rule.required().max(120),
    }),
    defineField({
      name: 'orbitHeadline',
      title: 'Orbit headline',
      type: 'string',
      group: 'story',
      initialValue: 'Sed do eiusmod tempor incididunt.',
      validation: (Rule) => Rule.required().max(120),
    }),
    defineField({
      name: 'indexHeadline',
      title: 'Index headline',
      type: 'string',
      group: 'story',
      initialValue: 'Ut enim ad minim veniam.',
      validation: (Rule) => Rule.required().max(120),
    }),
    defineField({
      name: 'chaptersHeadline',
      title: 'Chapters headline',
      type: 'string',
      group: 'story',
      initialValue: 'Duis aute irure dolor.',
      validation: (Rule) => Rule.required().max(120),
    }),
    defineField({
      name: 'apertureHeadline',
      title: 'Aperture headline',
      type: 'string',
      group: 'story',
      initialValue: 'Excepteur sint occaecat cupidatat.',
      validation: (Rule) => Rule.required().max(120),
    }),
    defineField({
      name: 'fallbackLabel',
      title: 'Accessible-version label',
      type: 'string',
      group: 'accessible',
      initialValue: 'Lorem ipsum dolor',
      validation: (Rule) => Rule.required().max(60),
    }),
    defineField({
      name: 'fallbackHeadline',
      title: 'Accessible-version headline',
      type: 'string',
      group: 'accessible',
      initialValue: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      validation: (Rule) => Rule.required().max(120),
    }),
    defineField({
      name: 'fallbackDescription',
      title: 'Accessible-version description',
      type: 'text',
      rows: 3,
      group: 'accessible',
      initialValue:
        'Consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
      validation: (Rule) => Rule.required().max(240),
    }),
    defineField({
      name: 'closingLabel',
      title: 'Closing label',
      type: 'string',
      group: 'closing',
      initialValue: 'Lorem ipsum dolor',
      validation: (Rule) => Rule.required().max(60),
    }),
    defineField({
      name: 'closingHeadline',
      title: 'Closing headline',
      type: 'string',
      group: 'closing',
      initialValue: 'What should we make next?',
      validation: (Rule) => Rule.required().max(100),
    }),
    defineField({
      name: 'ctaLabel',
      title: 'Button label',
      type: 'string',
      group: 'closing',
      initialValue: 'Lorem ipsum',
      validation: (Rule) => Rule.required().max(60),
    }),
    defineField({
      name: 'ctaDestination',
      title: 'Button destination',
      type: 'string',
      group: 'closing',
      initialValue: 'contact',
      options: {
        list: [
          {title: 'Contact page', value: 'contact'},
          {title: 'Work page', value: 'work'},
        ],
        layout: 'radio',
      },
      validation: (Rule) => Rule.required(),
    }),
    defineField({name: 'seo', title: 'About-page SEO', type: 'seoFields', group: 'seo'}),
  ],
  initialValue: {
    openingLabel: 'Lorem ipsum dolor',
    openingHeadline: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    openingNote: 'Consectetur adipiscing',
    windingHeadline: 'Consectetur adipiscing elit.',
    orbitHeadline: 'Sed do eiusmod tempor incididunt.',
    indexHeadline: 'Ut enim ad minim veniam.',
    chaptersHeadline: 'Duis aute irure dolor.',
    apertureHeadline: 'Excepteur sint occaecat cupidatat.',
    fallbackLabel: 'Lorem ipsum dolor',
    fallbackHeadline: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    fallbackDescription:
      'Consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    closingLabel: 'Lorem ipsum dolor',
    closingHeadline: 'What should we make next?',
    ctaLabel: 'Lorem ipsum',
    ctaDestination: 'contact',
    seo: {noIndex: true},
  },
  preview: {prepare: () => ({title: 'About page', subtitle: 'Motion story and page copy'})},
})
