import {PlayIcon} from '@sanity/icons/Play'
import {defineField, defineType} from 'sanity'

export const reelPage = defineType({
  name: 'reelPage',
  title: 'About page',
  type: 'document',
  icon: PlayIcon,
  groups: [
    {name: 'intro', title: 'Opening', default: true},
    {name: 'fallback', title: 'Accessible version'},
    {name: 'closing', title: 'Closing action'},
    {name: 'seo', title: 'Search & sharing'},
  ],
  fields: [
    defineField({
      name: 'enabled',
      title: 'Show the About page',
      description: 'Makes the motion-led About page available at /about.',
      type: 'boolean',
      group: 'intro',
      initialValue: false,
    }),
    defineField({
      name: 'introEyebrow',
      title: 'Opening label',
      type: 'string',
      group: 'intro',
      initialValue: 'Lorem ipsum dolor',
      validation: (Rule) => Rule.required().max(60),
    }),
    defineField({
      name: 'introHeadline',
      title: 'Opening headline',
      type: 'string',
      group: 'intro',
      initialValue: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      validation: (Rule) => Rule.required().max(100),
    }),
    defineField({
      name: 'introCue',
      title: 'Scroll cue',
      type: 'string',
      group: 'intro',
      initialValue: 'Consectetur adipiscing',
      validation: (Rule) => Rule.required().max(50),
    }),
    defineField({
      name: 'fallbackEyebrow',
      title: 'Accessible-version label',
      type: 'string',
      group: 'fallback',
      initialValue: 'Lorem ipsum dolor',
      validation: (Rule) => Rule.required().max(60),
    }),
    defineField({
      name: 'fallbackHeadline',
      title: 'Accessible-version headline',
      type: 'string',
      group: 'fallback',
      initialValue: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      validation: (Rule) => Rule.required().max(120),
    }),
    defineField({
      name: 'fallbackDescription',
      title: 'Accessible-version explanation',
      type: 'text',
      rows: 3,
      group: 'fallback',
      description: 'Shown when motion is reduced or WebGL is unavailable.',
      initialValue: 'Consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
      validation: (Rule) => Rule.required().max(240),
    }),
    defineField({
      name: 'closingEyebrow',
      title: 'Closing label',
      type: 'string',
      group: 'closing',
      initialValue: 'Lorem ipsum dolor',
      validation: (Rule) => Rule.required().max(60),
    }),
    defineField({
      name: 'closingHeadline',
      title: 'Closing headline',
      type: 'string',
      group: 'closing',
      initialValue: 'What should we make next?',
      validation: (Rule) => Rule.required().max(100),
    }),
    defineField({
      name: 'ctaLabel',
      title: 'Button label',
      type: 'string',
      group: 'closing',
      initialValue: 'Lorem ipsum',
      validation: (Rule) => Rule.required().max(60),
    }),
    defineField({
      name: 'ctaDestination',
      title: 'Button destination',
      type: 'string',
      group: 'closing',
      initialValue: 'contact',
      options: {
        list: [
          {title: 'Contact page', value: 'contact'},
          {title: 'Work page', value: 'work'},
        ],
        layout: 'radio',
      },
      validation: (Rule) => Rule.required(),
    }),
    defineField({name: 'seo', title: 'About-page SEO', type: 'seoFields', group: 'seo'}),
  ],
  initialValue: {
    enabled: false,
    introEyebrow: 'Lorem ipsum dolor',
    introHeadline: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    introCue: 'Consectetur adipiscing',
    fallbackEyebrow: 'Lorem ipsum dolor',
    fallbackHeadline: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    fallbackDescription: 'Consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    closingEyebrow: 'Lorem ipsum dolor',
    closingHeadline: 'What should we make next?',
    ctaLabel: 'Lorem ipsum',
    ctaDestination: 'contact',
    seo: {noIndex: true},
  },
  preview: {
    select: {enabled: 'enabled'},
    prepare: ({enabled}) => ({
      title: 'About page',
      subtitle: enabled ? 'Visible in website navigation' : 'Hidden from website navigation',
    }),
  },
})
